### ISSUE TITLE
Copy constraint fails on comparison_flag component

### ISSUE THREAD

**Issue by makxenov** [NilFoundation/zkllvm-blueprint#200]
Component: [comparison_flag](https://github.com/NilFoundation/zkllvm-blueprint/blob/master/include/nil/blueprint/components/algebra/fields/plonk/non_native/comparison_flag.hpp#L220) 
Inputs: `28948022309329048855892746252171976963363056481941560715954676764349967630336` (aka `-1`), `1` 
Mode: `nil::blueprint::components::detail::comparison_mode::LESS_THAN`

[This copy-constraint](https://github.com/NilFoundation/zkllvm-blueprint/blob/master/include/nil/blueprint/components/algebra/fields/plonk/non_native/comparison_flag.hpp#L629) tries to compare the first input with `0` for some reason (and thus fails).

**Comment by Iluvmagick** [comment]
@makxenov this component would never be able to compare -1 with anything: it relies on compared elements fitting into `bits_amount` bits, which should be less than `BlueprintFieldType::modulus_bits`.
I'll add initialization aborts so that component does fail during initialization instead of silently being created in what is basically an incorrect state -- should have done that when moving from template parameters, which had `std::enable_if` to protect from this.

**Comment by Iluvmagick** [comment]
It's been implemented like this, because the comparison logic here basically relies on decomposing the element into bits while performing bitwise comparisons. Checking that the decomposition is correct gets significantly more difficult if we work with full-sized field elements.
